title: Angular.DE
description: ""
topic: Angular
url: "https://angular.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: angular_de
github_username:  jekyll
gtm_property: "GTM-T5VPDDK"
utm_source: "angular_de"
permalink: /artikel/:slug/
repository_url: "https://github.com/symetics/angular.de"
og_generator_enabled: true

navigation:
  banner:
    message: "<b>Angular Lifetime</b>: Dein deutschsprachiger Intensiv-Videokurs in Kombination mit wöchentlichem Live-Call!"
    href: "https://workshops.de/seminare-schulungen-kurse/angular-lifetime?utm_source=angular_de&utm_campaign=portal_ads&utm_medium=banner&utm_content=page-lifetime"

plugins_dir: ["_plugins/", "shared/plugins/"]

collections:
  books:
    output: true
    permalink: /buecher/:path/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      header_image: "header.jpg"
      toc: true
      language: "de"
  - scope:
      path: "_books" # an empty string here means all files in the project
    values:
      layout: "chapter"
  - scope:
      path: "_pages" # an empty string here means all files in the project
    values:
      layout: "page"
  - scope:
      path: "opengraph"
    values:
      image: true
      sitemap: false
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "shared/assets"
    values:
      sitemap: false

pagination:
  enabled: true
  per_page: 5
  permalink: '/seite/:num/'
  title: ':title - Seite :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/css
  sourcemap: never
autoprefixer:
  only_production: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - .gitignore
  - nginx.conf
  - cloudbuild.yaml
  - firebase-debug.log

# webrick:
#   headers:
#     Content-Security-Policy: "style-src 'self'"
