# local_backend: true
locale: 'de'
logo_url: https://angular.de/assets/img/logo.svg
backend:
  name: github
  repo: workshops-de/angular.de
  open_authoring: true
  base_url: https://angular.de
  auth_endpoint: /oauth/auth
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'article'
    label: 'Artikel'
    label_singular: 'Artikel'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: '{{slug}}/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'Author'
        name: 'author'
        widget: 'relation'
        collection: 'authors'
        search_fields: ['name']
        value_field: '{{slug}}'
        display_fields: ['name']
      - { label: 'Publish Date', name: 'published_at', widget: 'datetime' }
      - { label: 'Header Source', name: 'header_source', widget: 'hidden', required: false}
      - label: 'Header Image'
        name: 'header_image'
        widget: 'file'
        media_library:
          config:
            max_file_size: 440000
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    sortable_fields: ['title', 'author', 'published_at']
  - name: 'authors'
    label: 'Autoren'
    label_singular: 'Autor'
    folder: '_data/users/'
    create: true
    slug: '{{slug}}'
    extension: yaml
    editor:
      preview: false
    fields:
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Gravatar UID', name: 'gravatar_uid', widget: 'string' }
      - { label: 'Github', name: 'github', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string' }
      - { label: 'Stadt', name: 'city', widget: 'string' }
      - { label: 'Ist Team-Mitglied?', name: 'team', widget: 'boolean' }
      - { label: 'Ist Trainer:in?', name: 'trainer', widget: 'boolean' }
      - { label: 'Ist GDE?', name: 'gde', widget: 'boolean' }
      - { label: 'Intro', name: 'intro', widget: 'text' }
      - { label: 'Bio', name: 'bio', widget: 'text' }
      - { label: 'started_with_angular', name: 'started_with_angular', widget: 'hidden' }
      - { label: 'why_angular_de_team', name: 'why_angular_de_team', widget: 'hidden' }
      - { label: 'best_workshop_memory', name: 'best_workshop_memory', widget: 'hidden' }
